name: Build and Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version Number (e.g., 1.3, 2.0.0)'
        required: true
        default: '1.0.0'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Update Version
        run: npm version ${{ github.event.inputs.version }} --no-git-tag-version

      - name: Install Dependencies
        run: npm install

      - name: Build and Package App
        run: npm run package

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.event.inputs.version }}
          name: Release v${{ github.event.inputs.version }}
          files: dist/*.exe
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
